[package]
name = "steel-plugin-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
mlua.workspace = true
clap.workspace = true
walkdir.workspace = true

tar.workspace = true
flate2.workspace = true
zstd.workspace = true
zip.workspace = true

thiserror.workspace = true
anyhow.workspace = true

[lints]
workspace = true
