package host:plugin-sdk@0.1.0;

interface plugin-api {
    on-enable: func();
    on-disable: func();

    rpc: func(method-name: string, data: list<u8>) -> option<list<u8>>;
    event-handler: func(handler-id: u32, data: list<u8>);
}

world plugin-world {
    import logging;
    import object;
    import rpc;

    export plugin-api;
}