package host:plugin-sdk@0.1.0;

interface rpc {
    record plugin-id {
        id: u32,
    }

    resolve-plugin: func(name: string) -> option<plugin-id>;
    dispatch: func(plugin-id: plugin-id, method-name: string, data: list<u8>) -> option<list<u8>>;
}
