[package]
name = "steel-plugin-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
steel-plugin-core.workspace = true

semver.workspace = true

syn = { workspace = true, features = ["full"] }
quote.workspace = true
proc-macro2.workspace = true
proc-macro-crate.workspace = true

[lints]
workspace = true
